<?php
$routes = array(
  'ServiceController' => array(
    'services' => 'service',
    'teacher' => 'teacher',
    'director' => 'director',
    'organization_add' => 'addorganization',
    'org_groups' => 'orggroups',
    'org_users' => 'orgusers',
    'orgupdategroups' => 'orgupdategroups',
    'orgupdateusers' => 'orgupdateusers',
    'check_group/([0-9]+)' => 'check/$1',
    'exclude_user/([0-9]+)' => 'exclude/$1'
  ),
  'TestController' => array(
    'testview/([0-9]+)' => 'testview/$1',
    'tests' => 'tests',
    'test/([0-9]+)' => 'test/$1',
    'updatefavorite' => 'updatefavorite',
    'updatetests' => 'updatetests',
    'constructor' => 'constructor',
    'sendques' => 'sendques',
    'infoinserting' => 'infoinserting',
    'formchecking' => 'formchecking',
    'timechecking' => 'timechecking',
    'checktest/([0-9]+)' => 'checktest/$1'
  ),
  'GroupController' => array(
    'groups' => 'groups',
    'group-requests' => 'requests',
    'updategroups' => 'updategroups',
    'updategrouprequests' => 'updategrouprequests',
    'requestgroupdeleted' => 'requestgroupdeleted',
    'group-search' => 'search',
    'requestadding' => 'requestadding',
    'group/([0-9]+)' => 'group/$1',
    'groupaction' => 'groupaction',
    'updaterecords' => 'updaterecords',
    'putlike' => 'putlike',
    'addcomment' => 'addcomment',
    'add-record/([0-9]+)' => 'addrecord/$1',
    'news' => 'news',
    'group_add' => 'add'
  ),
  'FriendController' => array(
    'friends' => 'friends',
    'updatefriends' => 'update_friends',
    'friend_deleted' => 'frienddeleted',
    'requests' => 'requests',
    'updaterequests' => 'updaterequests',
    'friendremove' => 'frienddeleted',
    'friendaccepting' => 'friendaccept',
    'myrequests' => 'myrequests',
    'request_deleted' => 'frienddeleted',
    'updatemyrequests' => 'updatemyrequests',
    'view/([0-9]+)' => 'view/$1',
    'friendaction' => 'friendaction',
    'friend-search' => 'search',
    'updatesearchfriend' => 'updatesearchfriend',
    'friendadding' => 'friendadding'
  ),
  'UserController' => array(
    'roles' => 'role',
    'role/([0-9]+)' => 'roleedit/$1',
    'my' => 'my',
    'logout' => 'logout',
    'settings' => 'settings',
    'describe' => 'describe',
    'send__setting_form' => 'sendsettingform',
    'update_privacy' => 'updateprivacy',
    'exit_org' => 'exitorg',
    'update_org' => 'updateorg',
    'add_org' => 'addorg',
    'upload_file' => 'upload',
    'delete_img' => 'deleteimg',
    'deletefavorite' => 'deletefavorite',
    'marks' => 'marks'
  ),
  'MessageController' => array(
    'addmsg' => 'addmsg',
    'getchat' => 'getchat',
    'readmsg' => 'readmsg',
    'im' => 'im',
    'chat/([0-9]+)' => 'chat/$1',
    'updateim' => 'updateim',
  ),
  'AuthController' => array(
    'vkauth/?code=([a-z]+)' => 'vkauth/$1',
    'auth' => 'auth',
  ),
  'MainController' => array(
      'search' => 'search',
      'report/([a-z]+)' => 'report/$1',
      'privacy' => 'privacy',
      '' => 'index'
    )
);
